config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'pages#home'
  
  get "/projects/new_card" => "projects#new_card", as: "new_card"

  resources :projects, :only => [:new, :create, :edit, :update, :show, :index] do
    resources :proposals, :only => [:new, :create, :edit, :update, :show, :index]
  end

  post "/projects/create_card" => "projects#create_card", as: "create_card"

  post "/projects/debit_card" => "projects#debit_card", as: "debit_card"

  resources :users, :only => [:show]
  resource :user, :only => [] do
    member do
      get :me
      get :edit
      put :update, :as => :update_profile
    end
  end

  resources :messages do
    collection do
      get 'outbox'
    end
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  
  has_many :replies, :class_name => "Message"
  belongs_to :original_message, :class_name => "Message", :foreign_key => :message_id
  belongs_to :sender, :class_name => "User", :foreign_key => :sender_id
  belongs_to :receiver, :class_name => "User", :foreign_key => :recipient_id

  validates :sender_id, :presence => true
  validates :recipient_id, :presence => true
  validates :body, :presence => true

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :authenticate_user!
	
	def index
		@user_messages = current_user.incoming_messages 
		@pages = @user_messages.paginate(:page => params[:page], :per_page => 5).order('created_at DESC')
	end

  def outbox
    @user_messages = current_user.outgoing_messages 
    @pages = @user_messages.paginate(:page => params[:page], :per_page => 5).order('created_at DESC')
  end
  
  def show
    @message = Message.find(params[:id]) 
    @reply = Message.new(:receiver => @message.sender, :message_id => @message.id)
    @message.update( read: true )
  end

  def destroy
  	@message = Message.find(params[:id])
  	@message.destroy!
  	redirect_to messages_path
  end

  def create  
    @reply = Message.new(message_params)
    @reply.sender = current_user
    if @reply.save
      respond_to do |format|
        
        format.html do
          flash[:notice] = "Your reply has been sent"
          redirect_to messages_path
        end

        format.js 

      end

    else
      respond_to do |format|
        format.html do
          @message = Message.find(@reply.message_id)
          render :show
        end
      end
    end
  end

  private
  def message_params
    params.require(:reply).permit(:recipient_id, :body, :message_id)
  end

end

app/helpers/messages_helper.rb
module MessagesHelper

  def status_read(message)
    if message.read?
      "read"
    else
      "unread"
    end
  end
end

app/views/messages/_message.html.erb
<div class="message-wrapper">
  <h2 id="message-subject"><%= message.subject %></h2>
  <p><%= message.body %></p>
  <p><%= message.created_at %></p>
</div>

app/views/messages/create.js.erb
$('#messages').append("<%= j(render partial: 'messages/message', locals: { :message => @reply }) %>");

app/views/messages/index.html.erb
<h2>Inbox</h2>

<%= link_to 'outbox', outbox_messages_path %>
<div class="messages">
<% @pages.each do |m| %>
  <div id="<%= status_read(m) %>">
    <div id="one_mess">
      <p id="subject"> <%= m.subject %> </p>
      <p id="user"> <%= m.sender_id %> <p>
      <p class="btn"><%= link_to 'show', message_path(m) %></p>
      <p class='btn'><%= link_to 'delete', message_path(m), :method => :delete, data: {confirm: "Are you sure?"} %></p>   
    </div>
  </div>
<%end%>
<div class="apple_pagination"> <%= will_paginate @pages %></div>
</div>

app/views/messages/outbox.html.erb
<h2>Outbox</h2>


<%= link_to 'Inbox', messages_path %>
<div class="messages">
<% @pages.each do |m| %>
    <div id="one_mess">
      <p id="subject"> <%= m.subject %> </p>
      <p id="user"> <%= m.recipient_id %> <p>
      <p><%= link_to 'show', message_path(m) %></p>
      <p><%= link_to 'delete', message_path(m), :method => :delete, data: {confirm: "Are you sure?"} %></p>   
    </div>
<%end%>
<div class="apple_pagination"> <%= will_paginate @pages %></div>
</div>

app/views/messages/show.html.erb
<div id="messages">
    <%= render partial: "messages/message", :locals => { :message => @message } %>
</div>

<%= link_to 'Delete', message_path(@message), :method => :delete, class: "btn", data: {confirm: "Are you sure?"}%>
<%= link_to 'Inbox', messages_path, class: "btn" %>
<%= link_to 'Reply', message_path(@message), class: 'btn', id: "reply-button" %>

<%= @reply.errors.full_messages %>

<%= form_for :reply, url: messages_path, :method => :post, html: { id: "reply-form" }, :remote => true do |m| %>

  <%= m.hidden_field :recipient_id %><br />
  <%= m.hidden_field :message_id %><br />
  <%= m.label :body %><br />
  <%= m.text_area(:body, cols: 50, rows: 20, placeholder: 'Write your reply here...', class: "form-control", rows: "5") %><br />
  <%= m.submit 'send' %>
<% end %>