config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'pages#home'
  
  get "/projects/new_card" => "projects#new_card", as: "new_card"

  resources :projects, :only => [:new, :create, :edit, :update, :show, :index] do
    resources :proposals, :only => [:new, :create, :edit, :update, :show, :index]
  end

  post "/projects/create_card" => "projects#create_card", as: "create_card"

  post "/projects/debit_card" => "projects#debit_card", as: "debit_card"

  resources :users, :only => [:show]
  resource :user, :only => [] do
    member do
      get :me
      get :edit
      put :update, :as => :update_profile
    end
  end

  resources :messages do
    collection do
      get 'outbox'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   validates_uniqueness_of :username
   validates_presence_of :username
   validates_presence_of :type

   has_many :expertise
   has_many :skills, :through => :expertise

   has_many :user_languages
   has_many :languages, :through => :user_languages

   has_many :incoming_messages, :class_name => "Message", :foreign_key => :recipient_id
   has_many :outgoing_messages, :class_name => "Message", :foreign_key => :sender_id

   mount_uploader :avatar, AvatarUploader

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  before_filter :assign_current_user, :only => [:me, :edit, :update]
  before_filter :all_projects, :only => [:me, :show]

  def me
    render :template => "users/#{current_user.type.downcase}"
  end

  def show
    @user = User.find(params[:id])
    render :template => "users/#{current_user.type.downcase}"
  end

  def edit 
    @languages = Language.all
    @skills = Skill.all
  end

  def update
    @user.update(allowed_params)
    redirect_to me_user_path
  end

  private
  def allowed_params
    params.require(:user).permit(:first_name, :last_name, :address, :username, :type, :birthday, :location, :about, :avatar, :language_ids => [], :skill_ids => [] )
  end

  def assign_current_user
    @user = current_user
  end

  def all_projects
    @projects = Project.all
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_show.html.erb
<div id="partial-left-half">
  <h3>Profile of <%= @user.username %></h3>
  <% if @user.id == current_user.id %>
    <%= link_to "Edit Profile", edit_user_path(@user), class: "edit-user"  %>
<% end %>
  <hr />
  <h4>About this <%= @user.type %></h4>
  <p><%= @user.about %></p>
  <hr />

  <ul>
    <li>Account type: <b><%= @user.type %></b></li>
    <li>Location: <b><%= @user.location %></b></li>
    <li>Skills:
      <% @user.skills.each do |skill| %>
        <b><%= skill.name %> | </b>
    <% end %>
    </li>
    <li>Languages:
      <% @user.languages.each do |language| %>
        <b><%= language.name %> | </b>
    <% end %>
    </li>
    <hr />
  </ul>
</div>
<div id="partial-right-half">
  <%= image_tag(@user.avatar.url , class: "avatar") if @user.avatar? %>
</div>

app/views/users/buyer.html.erb
<div id="profile-container">
  <div id="partial-container">
    <%= render partial: "users/show", :locals => { :user => @user } %>
  </div>
  <div id="tendered-projects" class="clear-both">
    <div class="row">
      <h4><%= @user.username %>'s Projects</h4>
      <hr />
      <% @user.projects.each do |project| %>
        <div class="col-md-4 profile-project">
        <%= project.title %>
        <% if @user.id == current_user.id %>
          <%= link_to "Edit", edit_project_path(project.id), class: "edit-project"  %>
      </div>
    <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/users/creative.html.erb
<div id="profile-container">
  <div id="partial-container">
    <%= render partial: "users/show", :locals => { :user => @user } %>
  </div>
  <div id="relevant-projects" class="clear-both">
    <div class="row">
      <h4><%= @user.username %>'s Relevant Projects</h4>
      <hr />
      <% @user.projects.each do |project| %>
        <div class="col-md-4 profile-project">
        <%= link_to project.title, project_path(project.id), class: "show-project"  %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="profile-page edit">
  <h2>Edit Profile Page</h2>

  <%= bootstrap_form_for :user, url: update_profile_user_path, :method => :put do |f| %>

    <%= image_tag(@user.avatar.url , class: "avatar") if @user.avatar? %>

  <%= field_set_tag do %>
  <%= f.text_field :username %>
<% end %>

  <%= field_set_tag do %>
  <%= f.text_field :location %>
<% end %>

  <%= field_set_tag do %>
  <%= f.text_area(:about, :cols => 50, :rows => 20, :placeholder => "Tell us about yourself ... ", :class => "about") %>
<% end %>

  <%= field_set_tag do %>
  <%= f.file_field(:avatar, accept: 'image/png,image/gif.image/jpeg') %>
<% end %>

  <div id ="languages" class="form-section">
    <h4>Languages</h4>
    <%= collection_select(:user, :language_ids, @languages, :id, :name,{},{multiple:true}) %>
  </div>

  <div id ="skills" class="form-section">
    <h4>Skills</h4>
    <%= collection_select(:user, :skill_ids, @skills, :id, :name,{},{multiple:true}) %>
  </div>

  <%= field_set_tag do %>
    <%= f.file_field(:avatar, accept: 'image/png,image/gif.image/jpeg') %>
  <% end %>


  <%= submit_tag "Update", class: "btn btn-success" %>

<% end %>
</div> 