config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'pages#home'
  
  get "/projects/new_card" => "projects#new_card", as: "new_card"

  resources :projects, :only => [:new, :create, :edit, :update, :show, :index] do
    resources :proposals, :only => [:new, :create, :edit, :update, :show, :index]
  end

  post "/projects/create_card" => "projects#create_card", as: "create_card"

  post "/projects/debit_card" => "projects#debit_card", as: "debit_card"

  resources :users, :only => [:show]
  resource :user, :only => [] do
    member do
      get :me
      get :edit
      put :update, :as => :update_profile
    end
  end

  resources :messages do
    collection do
      get 'outbox'
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

   validates_length_of :title, :minimum => 4, :allow_blank => false  
   validates_length_of :description, :minimum => 10, :allow_blank => false 
   validates_length_of :about, :minimum => 10, :allow_blank => false 
   validates_presence_of :closing_date

   has_many :requisite_skills
   has_many :skills, :through => :requisite_skills

   has_many :proposals
   has_many :creatives, :through => :proposals

   belongs_to :buyer

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  before_filter :find_a_project, :only => [:update, :edit, :show]

  def new
    @project = Project.new(:buyer_id => current_user.id)
    @skills = Skill.all
  end

  def create
    @project = Project.new(params_for_project)
    if @project.save
      flash[:notice] = "Your project has been saved"
      redirect_to new_card_path
    else 
      @skills = Skill.all
      render :new
    end
  end

  def create_card
    # {"payment_response"=>{"cards"=>{"0"=>{"href"=>"/cards/CC1zTBYNIzSsbMURBGnW5Y5J", "id"=>"CC1zTBYNIzSsbMURBGnW5Y5J"}}, "status_code"=>"201"}}
    card = Balanced::Card.fetch(params[:payment_response][:cards].first[1][:href])
    buyer = current_user
    address = [] || buyer.address
    if card.is_verified == true
      current_user.update_attribute(:balanced_card_uri, card.href)
      # Adress object for balanced 
      unless buyer.address?
        street_address = card.address[:line1]
        city = card.address[:city]
        state = card.address[:state]
        country = "US"
        postal_code = card.address[:postal_code]
        address << "#{street_address},#{city},#{state},#{postal_code},#{country}"
        buyer.update_attribute(:address, address)
      end
      # Find or create balanced customer
      customer = buyer.find_or_create_balanced_customer(address)
      customer

      # Associate card
      if card.links[:customer] == nil # Check card's fetched instance for an associated customer
        card.associate_to_customer(customer.href)
      end

      begin
        @debit = card.debit(
          :amount => (10 * 100).to_i,
          :appears_on_statement_as => "Charged for Book",
          :description => "Charged for Book"
        )
        if @debit.status == "succeeded"
          render :js => "window.location.href='"+root_path+"'" 
          flash[:notice] = "Escrow was succesfully funded. "
        else
          render :js => "window.location.href='"+root_path+"'" 
          flash[:notice] = "Escrow was not succesfully funded. Please check your account details."
        end
      rescue Balanced::Error => ex 
        render :js => "window.location.href='"+root_path+"'" 
        flash[:alert] = ex.message.split("card-declined: ")[1].split(" --")[0] unless ex.nil?
      end
    end
  end

  def new_card
  end  

  def show
  end

  def index
    @projects = Project.all
  end

  def edit
    @skills = Skill.all
  end

  def update
    if  @project.update(params_for_project)
      flash[:notice] = "Your project has been saved"
      redirect_to new_project_path
    else
      @skills = Skill.all
      render :new
    end
  end

  private
  def params_for_project
    params.require(:project).permit(:title, :description, :about, :closing_date, :buyer_id, :skill_ids => [])
  end

  def find_a_project
    @project = Project.find(params[:id])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<div class="project-page edit">
  <h2>Edit Project Page</h2>

  <% if @project.errors.any? %>
    <% @project.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  <% end %>

  <%= form_for :project, url: project_path(@project), :method => :put do |f| %>

    <h3><%= @project.title %></h3>

    <%= field_set_tag do %>
    <%= f.label :description %>
  <%= f.text_area(:description, :cols => 50, :rows => 20, :placeholder => "Tell us about the project ... you have to write a minimum of 10 characters.", :class => "description") %>
<% end %>

  <%= field_set_tag do %>
    <%= f.label :about %>
  <%= f.text_area(:about, :cols => 50, :rows => 20, :placeholder => "Tell us about yourself ... You have to write a minimum of 10 characters", :class => "about") %>
<% end %>

  <div><%= f.label :closing_date %><br />
    <%= f.date_select(:closing_date, { include_blank: true, start_year: Time.now.year, end_year: (Time.now.year + 13) }) %></div>

  <div id ="project-skills" class="form-section">
    <h4>Skills</h4>
    <%= collection_select(:project, :skill_ids, @skills, :id, :name,{}, {multiple:true}) %>
  </div>

  <button type="submit" class="btn btn-default"><%= submit_tag "Update Project" %></button>

<% end %>
</div> 

app/views/projects/index.html.erb
<h4>Index of Projects</h4>

<% @projects.each do |project| %>
  <li>Project Title: <%= link_to project.title, project_path(project.id), class: "show-project" %><br /><b> Tendered by:<% binding.pry if project.buyer.nil? %> <%= link_to project.buyer.username, user_path(project.buyer) %></b></li> <hr />
<% end %>

app/views/projects/new.html.erb
<div class="profile-page">
  <h2>Add Project</h2>

  <% if @project.errors.any? %>
    <% @project.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  <% end %>

  <%= bootstrap_form_for @project do |f| %>

    <%= f.hidden_field :buyer_id %>

    <%= field_set_tag do %>
  <%= f.text_field :title %>
  <% end %>

  <%= field_set_tag do %>
  <%= f.text_area(:description, :cols => 50, :rows => 20, :placeholder => "Tell us about the project ... ", :class => "about") %>
  <% end %>

  <%= field_set_tag do %>
  <%= f.text_area(:about, :cols => 50, :rows => 20, :placeholder => "Tell us about yourself ... ", :class => "about") %>
  <% end %>

    <%= f.date_select(:closing_date, { include_blank: true, start_year: Time.now.year, end_year: (Time.now.year + 13) }) %>

  <div id ="project-skills" class="form-section">
    <h4>Skills</h4>
    <%= collection_select(:project, :skill_ids, @skills, :id, :name,{}, {multiple:true}) %>
  </div>


  <%= submit_tag "Update", class: "btn btn-success" %>

<% end %>
</div> 

app/views/projects/new_card.html.erb
<%= form_for "#" do |f| %>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="alert alert-info">
        <p>Do not provide real credit card or bank account details into these forms. Instead use <a href="https://docs.balancedpayments.com/current/overview.html#test-credit-card-numbers" class="alert-link" target="_blank">test cards</a> and <a href="https://docs.balancedpayments.com/current/overview.html#test-bank-account-numbers" class="alert-link" target="_blank">bank accounts</a>.</p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <button type="button" id="populate" class="btn btn-default pull-right" style="margin-bottom: 20px;">Populate Test Data</button>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Tokenize Credit Card</h3>
        </div>
        <div class="panel-body">
          <form role="form" class="form-horizontal">
            <div class="form-group">
              <label class="col-lg-5 control-label">Name on Card</label>
              <div class="col-lg-5">
                <input type="text" id="cc-name" class="form-control" autocomplete="off" placeholder="John Doe" />
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-5 control-label">Card Number</label>
              <div class="col-lg-5">
                <input type="text" id="cc-number" class="form-control" autocomplete="off" placeholder="4111111111111111" maxlength="16" />
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-5 control-label">Expiration</label>
              <div class="col-lg-2">
                <input type="text" id="cc-ex-month" class="form-control" autocomplete="off" placeholder="01" maxlength="2" />
              </div>
              <div class="col-lg-2">
                <input type="text" id="cc-ex-year" class="form-control" autocomplete="off" placeholder="2013" maxlength="4" />
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-5 control-label">Security Code (CSC)</label>
              <div class="col-lg-2">
                <input type="text" id="ex-csc" class="form-control" autocomplete="off" placeholder="453" maxlength="4" />
              </div>
            </div>
            <!-- <a id="cc-submit" class="btn btn-large btn-primary pull-right">Tokenize</a> -->
      <%=f.submit "Add card", id: "cc-submit"%>
      <%end%>
      
          </form>
        </div>
      </div>
    </div>
  </div>


<div class="row">
    <div id="response" class="col-lg-12" style="display: none;">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Response</h3>
        </div>
        <div class="panel-body">
          <pre></pre>
        </div>
      </div>
    </div>
  </div>

app/views/projects/show.html.erb
<div class="profile-page">
  <h3><%= @project.title %></h3>
  <hr />

  <h4>About the Buyer:</h4>
  <p><%= @project.about %></p>
  <hr />

  <h4>About the Project:</h4>
  <p><%= @project.description %></p>
  <hr />

  <ul>
    <li>Closing date: <%= @project.closing_date %></li>
    <li>Requisite Skills:
      <% @project.skills.each do |skill| %>
        <%= skill.name %>
    <% end %>
    </li>
  </ul>
  <hr />

  <% if current_user.type == "Creative" %>
  <button class="btn btn-default"><%= link_to 'Submit a Pitch', new_project_proposal_path(@project), class: "show-proposal" %></button><br />
<hr />
<% end %>

  <h4>Submitted pitches for this project:</h4>

<% @project.proposals.each do |proposal| %>
  <li>Proposal Title: <%= link_to proposal.title, project_proposal_path(@project, proposal.id), class: "show-proposal" %><br /><b> Pitched by: <%= link_to proposal.creative.username, user_path(proposal.creative) %></b></li> <hr />
<% end %>
</ul>

</div>